<a href="https://colab.research.google.com/github/nlp2bok/fintech_/blob/wsy_dev/%EC%BD%9C%EA%B8%88%EB%A6%AC%EC%9B%B9%ED%81%AC%EB%A1%A4%EB%A7%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import urllib
import time
import re
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

In [0]:
date_list = []
num_list = []

for i in range(1,62):
    page = 'https://finance.naver.com/marketindex/interestDailyQuote.nhn?marketindexCd=IRR_CALL&page='+str(i)
    html = urlopen(page) 
    source = BeautifulSoup(html.read(), "html.parser")
    a = source.find_all('td', class_='date')
    b = source.find_all('td', class_='num')

    
    for i in range(7):
        date = a[i].text.replace('\n', "").replace('\t', '')
        date_list.append(date)
    
    for i in range(2, 21, 3):
        num_list.append(b[i].text.replace('\n', "").replace('\t', ''))

a = pd.DataFrame({"date" : date_list, "ratio" : num_list})

In [0]:
a

           date     ratio
0    2019.05.20   + 1.15%
1    2019.05.17    -0.57%
2    2019.05.16    -0.57%
3    2019.05.15   + 1.73%
4    2019.05.14    -1.14%
5    2019.05.13   + 0.57%
6    2019.05.10   + 0.58%
7    2019.05.20   + 1.15%
8    2019.05.17    -0.57%
9    2019.05.16    -0.57%
10   2019.05.15   + 1.73%
11   2019.05.14    -1.14%
12   2019.05.13   + 0.57%
13   2019.05.10   + 0.58%
14   2019.05.20   + 1.15%
15   2019.05.17    -0.57%
16   2019.05.16    -0.57%
17   2019.05.15   + 1.73%
18   2019.05.14    -1.14%
19   2019.05.13   + 0.57%
20   2019.05.10   + 0.58%
21   2019.05.20   + 1.15%
22   2019.05.17    -0.57%
23   2019.05.16    -0.57%
24   2019.05.15   + 1.73%
25   2019.05.14    -1.14%
26   2019.05.13   + 0.57%
27   2019.05.10   + 0.58%
28   2019.05.20   + 1.15%
29   2019.05.17    -0.57%
..          ...       ...
397  2019.05.13   + 0.57%
398  2019.05.10   + 0.58%
399  2019.05.20   + 1.15%
400  2019.05.17    -0.57%
401  2019.05.16    -0.57%
402  2019.05.15   + 1.73%
403  2019.05.14    -1.14%
404  2019.05.13   + 0.57%
405  2019.05.10   + 0.58%
406  2019.05.20   + 1.15%
407  2019.05.17    -0.57%
408  2019.05.16    -0.57%
409  2019.05.15   + 1.73%
410  2019.05.14    -1.14%
411  2019.05.13   + 0.57%
412  2019.05.10   + 0.58%
413  2019.05.20   + 1.15%
414  2019.05.17    -0.57%
415  2019.05.16    -0.57%
416  2019.05.15   + 1.73%
417  2019.05.14    -1.14%
418  2019.05.13   + 0.57%
419  2019.05.10   + 0.58%
420  2019.05.20   + 1.15%
421  2019.05.17    -0.57%
422  2019.05.16    -0.57%
423  2019.05.15   + 1.73%
424  2019.05.14    -1.14%
425  2019.05.13   + 0.57%
426  2019.05.10   + 0.58%

[427 rows x 2 columns]